// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using companyOSINT.Infrastructure.Data;

#nullable disable

namespace companyOSINT.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("companyOSINT.Domain.Entities.ApiToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenPrefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_ApiTokens_TokenHash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ApiTokens_UserId");

                    b.ToTable("ApiTokens");
                });

            modelBuilder.Entity("companyOSINT.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Activity")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateLastChecked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FederalState")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("RegisterArt")
                        .HasColumnType("text");

                    b.Property<string>("RegisterNummer")
                        .HasColumnType("text");

                    b.Property<string>("RegisteredAddress")
                        .HasColumnType("text");

                    b.Property<string>("RegisteredOffice")
                        .HasColumnType("text");

                    b.Property<string>("Registrar")
                        .HasColumnType("text");

                    b.Property<Guid?>("SectorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DateLastChecked")
                        .HasDatabaseName("IX_Companies_DateLastChecked");

                    b.HasIndex("PostalCode")
                        .HasDatabaseName("IX_Companies_PostalCode");

                    b.HasIndex("SectorId");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("companyOSINT.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dismissed")
                        .HasColumnType("text");

                    b.Property<string>("EndDate")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("Flag")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("MaidenName")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Position")
                        .HasColumnType("text");

                    b.Property<string>("ReferenceNo")
                        .HasColumnType("text");

                    b.Property<string>("StartDate")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("companyOSINT.Domain.Entities.DomainToSkip", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasDatabaseName("IX_DomainsToSkip_Domain");

                    b.ToTable("DomainsToSkip");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0685844-a46d-9f8d-4631-ddd35ae2da76"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "northdata.de"
                        },
                        new
                        {
                            Id = new Guid("2ae4cacb-bc4d-56f0-0630-6a3650099e98"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "northdata.com"
                        },
                        new
                        {
                            Id = new Guid("69b8870d-69f6-3b5e-fc48-059b24b0d201"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "firmenwissen.de"
                        },
                        new
                        {
                            Id = new Guid("ff9c0816-8db1-e04c-1755-291c873a9efd"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "companyhouse.de"
                        },
                        new
                        {
                            Id = new Guid("c5594f2d-350e-5d5a-9bed-bd409fc1caed"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "companyhouse.com"
                        },
                        new
                        {
                            Id = new Guid("a37dfbbd-99c1-37cc-651d-e7e128cbb234"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "unternehmensregister.de"
                        },
                        new
                        {
                            Id = new Guid("b226540a-5b51-c8d5-e76b-d079f3f0e1a5"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "handelsregister.de"
                        },
                        new
                        {
                            Id = new Guid("5ba00f85-a815-c40c-971d-535c0ec5c4c8"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "bundesanzeiger.de"
                        },
                        new
                        {
                            Id = new Guid("fcee17dd-c06b-b18c-4dd3-53d803b81dd7"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "dnb.com"
                        },
                        new
                        {
                            Id = new Guid("85fbbbfc-34c2-4b77-1bd0-af8708ceda1d"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "bisnode.de"
                        },
                        new
                        {
                            Id = new Guid("96c92ce4-b5c8-ce63-f2bf-ab18408d310e"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "creditreform.de"
                        },
                        new
                        {
                            Id = new Guid("440cac45-940d-094a-ae75-42869be6b47f"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "hoppenstedt.de"
                        },
                        new
                        {
                            Id = new Guid("69ac119d-0bc2-a0a4-bbbe-fe430a218a0b"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "gelbeseiten.de"
                        },
                        new
                        {
                            Id = new Guid("aca55a2d-0e3f-f6c1-1db6-d18d78615c3f"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "dasoertliche.de"
                        },
                        new
                        {
                            Id = new Guid("679e3a82-41d1-372c-7e6d-b0b1b387009a"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "11880.com"
                        },
                        new
                        {
                            Id = new Guid("65ad6b55-1efc-c1e5-3db4-dc1a7bd29eba"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "golocal.de"
                        },
                        new
                        {
                            Id = new Guid("9175967b-7a7b-1952-1d7e-ea0279fda3ec"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "yelp.de"
                        },
                        new
                        {
                            Id = new Guid("00cb64e5-5b0a-07e8-e6e4-6fed82e4333a"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "yelp.com"
                        },
                        new
                        {
                            Id = new Guid("216cea36-ca35-a48c-7997-c751d4bc4f6f"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "tripadvisor.de"
                        },
                        new
                        {
                            Id = new Guid("77de6af6-827e-74b3-f4b3-607c57f4ec3e"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "tripadvisor.com"
                        },
                        new
                        {
                            Id = new Guid("71032630-87a5-8361-7808-7fdc2f059297"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "kununu.com"
                        },
                        new
                        {
                            Id = new Guid("cf2aee9c-3450-6f82-4362-a5ea0fb46317"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "wlw.de"
                        },
                        new
                        {
                            Id = new Guid("1c9fb30b-1339-7bce-3d82-bd01d56cae4b"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "europages.de"
                        },
                        new
                        {
                            Id = new Guid("cacf4661-054c-534b-9b6b-0b5a6f6d185a"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "europages.com"
                        },
                        new
                        {
                            Id = new Guid("78ec4323-4ca0-a96e-d808-06345d31fd78"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "facebook.com"
                        },
                        new
                        {
                            Id = new Guid("d5c7813f-384d-bae6-8592-b0308cb31333"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "facebook.de"
                        },
                        new
                        {
                            Id = new Guid("63b44df5-0975-e040-e7f7-630fe327845e"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "linkedin.com"
                        },
                        new
                        {
                            Id = new Guid("7638babd-f43e-7a86-dfd6-54759bde6f73"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "xing.com"
                        },
                        new
                        {
                            Id = new Guid("0b46c68d-b0bb-7588-7ed6-7ed8fb316b1b"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "instagram.com"
                        },
                        new
                        {
                            Id = new Guid("c4d10579-2ce1-9354-3a44-d19fcd5f9356"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "twitter.com"
                        },
                        new
                        {
                            Id = new Guid("a323439a-6942-ab83-2474-4f3fdbd15200"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "x.com"
                        },
                        new
                        {
                            Id = new Guid("6652dd14-07c7-bd89-c806-364df4586335"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "youtube.com"
                        },
                        new
                        {
                            Id = new Guid("196949cb-eb20-bf99-8929-90332db2af70"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "tiktok.com"
                        },
                        new
                        {
                            Id = new Guid("887f5f46-e431-09cb-ba66-21dab2a4d6ee"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "wikipedia.org"
                        },
                        new
                        {
                            Id = new Guid("e1bd3c68-b4a2-f79c-13be-7802f671f892"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "wikidata.org"
                        },
                        new
                        {
                            Id = new Guid("f420591d-4bb4-a827-02bd-77c4f0536f5a"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "google.com"
                        },
                        new
                        {
                            Id = new Guid("0466f478-2e12-470a-c614-e876ec02533b"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "google.de"
                        },
                        new
                        {
                            Id = new Guid("57b524de-ea1d-7cea-f4b2-a5c00ef66fb7"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "apple.com"
                        },
                        new
                        {
                            Id = new Guid("0eba3dcd-ed37-edf3-fd42-ccc21e598e10"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "amazon.de"
                        },
                        new
                        {
                            Id = new Guid("3828a8a2-3864-a06c-4a56-94e8b58759e6"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "amazon.com"
                        },
                        new
                        {
                            Id = new Guid("4f1c9876-ee79-ff51-759c-02096918e1bb"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "ebay.de"
                        },
                        new
                        {
                            Id = new Guid("92e2c812-6ca4-2905-663c-d963419e4645"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Domain = "ebay.com"
                        });
                });

            modelBuilder.Entity("companyOSINT.Domain.Entities.PostalCode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("character(5)")
                        .IsFixedLength();

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code");

                    b.ToTable("PostalCodes");
                });

            modelBuilder.Entity("companyOSINT.Domain.Entities.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Sectors_Name");

                    b.ToTable("Sectors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d868e48-0c3e-732f-d9a1-5cc2b8870f8a"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Maschinenbau"
                        },
                        new
                        {
                            Id = new Guid("9e27184c-b36e-48ee-8d0e-db6c5476454e"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Automobilindustrie & Fahrzeugbau"
                        },
                        new
                        {
                            Id = new Guid("c2fa02d9-d311-3a6b-7840-bcf785641654"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Elektrotechnik & Elektronik"
                        },
                        new
                        {
                            Id = new Guid("f2d9f386-2630-7b9a-9b8e-40adeba9d510"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Chemie & Pharma"
                        },
                        new
                        {
                            Id = new Guid("78fb5b08-819b-e3a5-0a2f-387af7e92810"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Kunststoff & Gummi"
                        },
                        new
                        {
                            Id = new Guid("3db09bf9-9a08-4223-3004-f1a91bae0b1a"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Metallerzeugung & -verarbeitung"
                        },
                        new
                        {
                            Id = new Guid("fac5ef3b-31af-7ee2-87d2-c204ce7e8b7d"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Lebensmittelherstellung"
                        },
                        new
                        {
                            Id = new Guid("8b0f99ae-4219-ba20-ebdf-23825474a42a"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Holz- & Möbelindustrie"
                        },
                        new
                        {
                            Id = new Guid("9fa8b0a9-2da4-c7f1-4fff-071b0daa0420"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Textil & Bekleidung"
                        },
                        new
                        {
                            Id = new Guid("fcd616ac-7895-d1e0-a332-47ef62741328"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Papier & Druck"
                        },
                        new
                        {
                            Id = new Guid("a5e1985c-02f1-2afe-d70b-acf6e8204e07"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Glas, Keramik & Baustoffe"
                        },
                        new
                        {
                            Id = new Guid("55fbb727-1729-ff84-fcc4-f942379c28b2"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Medizintechnik"
                        },
                        new
                        {
                            Id = new Guid("0f3d3acb-72ac-833f-cad5-53c9982c0c45"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Luft- & Raumfahrttechnik"
                        },
                        new
                        {
                            Id = new Guid("1039c6ae-5b7b-4947-1c34-b43180e1c190"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Optik & Feinmechanik"
                        },
                        new
                        {
                            Id = new Guid("b011a47e-e375-6acb-5d0e-5e45ddbd3ed7"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Baugewerbe & Hochbau"
                        },
                        new
                        {
                            Id = new Guid("539b5f3d-5018-1263-66bb-8eb024e5e512"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tiefbau & Infrastruktur"
                        },
                        new
                        {
                            Id = new Guid("5cce7692-2613-d7b1-6b15-3c9b2d8fac0c"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gebäudetechnik & Haustechnik"
                        },
                        new
                        {
                            Id = new Guid("4e9c512d-38f5-55d1-3cf1-6de8f866f31d"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Immobilienwirtschaft"
                        },
                        new
                        {
                            Id = new Guid("e13e0398-7450-685c-28eb-7712afda0c21"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Architektur & Planung"
                        },
                        new
                        {
                            Id = new Guid("98e73429-d2aa-8349-dcda-83b6130a5dd0"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Großhandel"
                        },
                        new
                        {
                            Id = new Guid("0745ca62-8cd5-004b-c646-d312c460eff3"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Einzelhandel"
                        },
                        new
                        {
                            Id = new Guid("40553504-ee27-dbfd-8e99-c1d1f814c705"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Online-Handel & E-Commerce"
                        },
                        new
                        {
                            Id = new Guid("b8fbe765-7d15-43f2-0dae-d0aea3a46418"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Kraftfahrzeughandel"
                        },
                        new
                        {
                            Id = new Guid("253f9c40-d86b-da29-90cc-83db8eb3644c"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Softwareentwicklung"
                        },
                        new
                        {
                            Id = new Guid("5d908a40-ad70-1855-9cfe-22cbdda36174"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "IT-Dienstleistungen & Beratung"
                        },
                        new
                        {
                            Id = new Guid("8a3ae1f9-d07a-ce59-041c-a864add3258f"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Telekommunikation"
                        },
                        new
                        {
                            Id = new Guid("99a8b4a4-0d5f-114d-e80b-938711213f87"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Rechenzentren & Cloud-Dienste"
                        },
                        new
                        {
                            Id = new Guid("18cafd21-2bf7-3e57-e0c5-2f6a109882c2"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cybersecurity"
                        },
                        new
                        {
                            Id = new Guid("76e042eb-3c6f-9d8b-ab36-200c38f0e53d"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Unternehmensberatung"
                        },
                        new
                        {
                            Id = new Guid("525bf4e9-cc7d-b84f-a01f-d04c803bd82f"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Rechtsberatung"
                        },
                        new
                        {
                            Id = new Guid("4eeca4dc-7716-006b-3ce3-4548576fe4c8"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Steuerberatung & Wirtschaftsprüfung"
                        },
                        new
                        {
                            Id = new Guid("d8f723ec-513b-305b-5c21-3ea25d5af346"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Marketing & Werbung"
                        },
                        new
                        {
                            Id = new Guid("4605adb3-3d92-95e1-8f62-df6f0561f7c8"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Personaldienstleistung"
                        },
                        new
                        {
                            Id = new Guid("e4687531-43de-7492-9714-f3713e193903"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Facility Management"
                        },
                        new
                        {
                            Id = new Guid("742eb0f2-2263-87e8-66c2-cd4ca7d5ac1d"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sicherheitsdienstleistungen"
                        },
                        new
                        {
                            Id = new Guid("5cc310ed-ee43-afbf-2275-9983d00bf44c"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Reinigung & Gebäudedienste"
                        },
                        new
                        {
                            Id = new Guid("7f2ceda7-6a06-6e7e-381f-785ca3256879"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bankwesen"
                        },
                        new
                        {
                            Id = new Guid("49e5b835-f89f-2d9b-ca85-2ae72e051457"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Versicherungen"
                        },
                        new
                        {
                            Id = new Guid("0fad5f25-3f5d-1076-b243-154bdcbe8f7e"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Finanzdienstleistungen & Vermögensverwaltung"
                        },
                        new
                        {
                            Id = new Guid("bc05159f-064b-72ad-08be-edc71cf19f5d"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gesundheitswesen & Kliniken"
                        },
                        new
                        {
                            Id = new Guid("6d16fff8-1f9f-8dee-2708-641ee40aaa47"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Pflege & Betreuung"
                        },
                        new
                        {
                            Id = new Guid("58c8c2fd-1a39-1ff4-0c5f-7b48f181b83e"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sozialwesen"
                        },
                        new
                        {
                            Id = new Guid("07688fc8-a859-efb7-2dc4-52a756705914"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Spedition & Logistik"
                        },
                        new
                        {
                            Id = new Guid("c76472e0-b7e9-9632-53a5-4ef7a15db747"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Personenbeförderung"
                        },
                        new
                        {
                            Id = new Guid("d15ebff7-582c-a133-ce3c-ff12b083ddb4"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Schifffahrt & Hafenwirtschaft"
                        },
                        new
                        {
                            Id = new Guid("2cfb812d-7a2a-45f9-8de9-9d22aa92e10c"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Luftfahrt"
                        },
                        new
                        {
                            Id = new Guid("d09e1783-3d24-be6d-67f9-c51ed68baae6"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Energieversorgung"
                        },
                        new
                        {
                            Id = new Guid("237b98cd-368e-1c71-af02-c4ef04085753"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Erneuerbare Energien"
                        },
                        new
                        {
                            Id = new Guid("215e2621-bb61-f1b5-eb2b-5519dfa9d408"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Entsorgung & Recycling"
                        },
                        new
                        {
                            Id = new Guid("8ddd8e7f-67de-728e-0c49-8309bc2d9c4e"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Wasser- & Abwasserwirtschaft"
                        },
                        new
                        {
                            Id = new Guid("ab872864-74b7-9e6e-8e2f-68b3631ad5a8"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Verlagswesen"
                        },
                        new
                        {
                            Id = new Guid("e183a3b9-f2cc-a7d5-5d35-ecc18c96761a"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Film, TV & Rundfunk"
                        },
                        new
                        {
                            Id = new Guid("55755328-107b-2af6-51cf-d2d3bfc48756"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Öffentlichkeitsarbeit & PR"
                        },
                        new
                        {
                            Id = new Guid("5517a5b5-6f99-8c52-03f6-5ed8316fc14d"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bildung & Weiterbildung"
                        },
                        new
                        {
                            Id = new Guid("24776bed-f4cc-faa2-ceed-1566401cfa3a"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Forschung & Entwicklung"
                        },
                        new
                        {
                            Id = new Guid("a67562bf-d1dd-936f-f4c4-baccdcf789e3"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gastronomie"
                        },
                        new
                        {
                            Id = new Guid("ec24f9b4-3b45-fa0b-1583-b6036f7201d3"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hotellerie & Beherbergung"
                        },
                        new
                        {
                            Id = new Guid("6cbf6337-bd70-b6f7-bf62-2c992c707771"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tourismus & Reiseveranstaltung"
                        },
                        new
                        {
                            Id = new Guid("3fe1f230-425b-e1ba-5b4a-b50aff85cca9"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Event & Veranstaltung"
                        },
                        new
                        {
                            Id = new Guid("416009de-6361-d0be-d3d8-cd910cc3b900"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Landwirtschaft & Gartenbau"
                        },
                        new
                        {
                            Id = new Guid("cc6c3cc7-b102-1405-5974-663ce06578b8"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Forstwirtschaft & Holzwirtschaft"
                        },
                        new
                        {
                            Id = new Guid("43044823-6e0b-b25b-34b8-d44097c9c97b"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Handwerk"
                        },
                        new
                        {
                            Id = new Guid("0ac25a9f-5f47-6e68-12ce-0a82250fc291"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Design & Kreativwirtschaft"
                        },
                        new
                        {
                            Id = new Guid("ba76e261-0ad3-f9af-351c-4b7a53204e82"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sport & Freizeit"
                        },
                        new
                        {
                            Id = new Guid("827f4e9f-9050-b0eb-4042-e126bde0c7cb"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Kultur & Unterhaltung"
                        },
                        new
                        {
                            Id = new Guid("10836a6f-ff4d-8f9e-ed68-d6f9cdf639fb"),
                            DateCreated = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateModified = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bergbau & Rohstoffe"
                        });
                });

            modelBuilder.Entity("companyOSINT.Domain.Entities.Software", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateLastChecked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FoundAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WebsiteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteId")
                        .HasDatabaseName("IX_Software_WebsiteId");

                    b.ToTable("Software");
                });

            modelBuilder.Entity("companyOSINT.Domain.Entities.Tool", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FoundAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WebsiteId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebsiteId")
                        .HasDatabaseName("IX_Tools_WebsiteId");

                    b.ToTable("Tools");
                });

            modelBuilder.Entity("companyOSINT.Domain.Entities.UserProject", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserProjects_UserId");

                    b.ToTable("UserProjects");
                });

            modelBuilder.Entity("companyOSINT.Domain.Entities.UserProjectCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("ProjectId", "CompanyId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserProjectCompanies_ProjectId_CompanyId");

                    b.ToTable("UserProjectCompanies");
                });

            modelBuilder.Entity("companyOSINT.Domain.Entities.Website", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("AverageTimeToFirstByte")
                        .HasColumnType("double precision");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ConsentManagerFound")
                        .HasColumnType("boolean");

                    b.Property<int>("CookiesWithoutConsent")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateLastChecked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HttpResponseCode")
                        .HasColumnType("integer");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<bool>("IsSubdomain")
                        .HasColumnType("boolean");

                    b.Property<int>("RequestsWithoutConsent")
                        .HasColumnType("integer");

                    b.Property<bool>("SslValid")
                        .HasColumnType("boolean");

                    b.Property<string>("UrlImprint")
                        .HasColumnType("text");

                    b.Property<string>("UrlWebsite")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DateLastChecked")
                        .HasDatabaseName("IX_Websites_DateLastChecked");

                    b.ToTable("Websites");
                });

            modelBuilder.Entity("companyOSINT.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("companyOSINT.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("companyOSINT.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("companyOSINT.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("companyOSINT.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("companyOSINT.Domain.Entities.ApiToken", b =>
                {
                    b.HasOne("companyOSINT.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("companyOSINT.Domain.Entities.Company", b =>
                {
                    b.HasOne("companyOSINT.Domain.Entities.Sector", "Sector")
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("companyOSINT.Domain.Entities.Contact", b =>
                {
                    b.HasOne("companyOSINT.Domain.Entities.Company", "Company")
                        .WithMany("Contacts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("companyOSINT.Domain.Entities.Software", b =>
                {
                    b.HasOne("companyOSINT.Domain.Entities.Website", "Website")
                        .WithMany("Softwares")
                        .HasForeignKey("WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Website");
                });

            modelBuilder.Entity("companyOSINT.Domain.Entities.Tool", b =>
                {
                    b.HasOne("companyOSINT.Domain.Entities.Website", "Website")
                        .WithMany("Tools")
                        .HasForeignKey("WebsiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Website");
                });

            modelBuilder.Entity("companyOSINT.Domain.Entities.UserProject", b =>
                {
                    b.HasOne("companyOSINT.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("companyOSINT.Domain.Entities.UserProjectCompany", b =>
                {
                    b.HasOne("companyOSINT.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("companyOSINT.Domain.Entities.UserProject", "Project")
                        .WithMany("Companies")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("companyOSINT.Domain.Entities.Website", b =>
                {
                    b.HasOne("companyOSINT.Domain.Entities.Company", "Company")
                        .WithMany("Websites")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("companyOSINT.Domain.Entities.Company", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Websites");
                });

            modelBuilder.Entity("companyOSINT.Domain.Entities.UserProject", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("companyOSINT.Domain.Entities.Website", b =>
                {
                    b.Navigation("Softwares");

                    b.Navigation("Tools");
                });
#pragma warning restore 612, 618
        }
    }
}
